### ISSUE TITLE
missing 'net/http'

### ISSUE THREAD

**Issue by RedaBenh** [Skalar/google_distance_matrix#57]
I'm using the gem without rails and i notice that 'net/http' is not loaded with the gem google_distance_matrix !
I get this error :
```
uninitialized constant GoogleDistanceMatrix::Client::Net

        Net::HTTP.get_response uri
        ^^^
Did you mean?  Set
/Users/redabenh/git/gettaxilambda/vendor/bundle/ruby/3.2.0+1/gems/google_distance_matrix-0.6.5/lib/google_distance_matrix/client.rb:29:in `block in get'
/Users/redabenh/git/gettaxilambda/vendor/bundle/ruby/3.2.0+1/gems/activesupport-7.0.7/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/redabenh/git/gettaxilambda/vendor/bundle/ruby/3.2.0+1/gems/activesupport-7.0.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/redabenh/git/gettaxilambda/vendor/bundle/ruby/3.2.0+1/gems/activesupport-7.0.7/lib/active_support/notifications.rb:206:in `instrument'
/Users/redabenh/git/gettaxilambda/vendor/bundle/ruby/3.2.0+1/gems/google_distance_matrix-0.6.5/lib/google_distance_matrix/client.rb:26:in `get'
/Users/redabenh/git/gettaxilambda/vendor/bundle/ruby/3.2.0+1/gems/google_distance_matrix-0.6.5/lib/google_distance_matrix/matrix.rb:117:in `load_matrix'
/Users/redabenh/git/gettaxilambda/vendor/bundle/ruby/3.2.0+1/gems/google_distance_matrix-0.6.5/lib/google_distance_matrix/matrix.rb:73:in `data'
lambda_function.rb:41:in `lambda_handler'
lambda_function_test.rb:8:in `<main>'

``` 
The error can be fixed easily by requiring the net/http on the top of my script
``` 

require 'net/http'

``` 
I wonder if there a dependency with rails , because it works fine with rails application ? 

Context of my test:
Rails 5.2.8.1
ruby 3.2.0preview1 (2022-04-03 master f801386f0c) [arm64-darwin21]
OS: MacOS Monterey 2.0.1 ( Apple M1 pro)

**Comment by thhermansen** [comment]
I have pushed a new version which requires net/http. Hope it solves the issue for you.
