### ISSUE TITLE
When trying to use Google API credentials I get #<ArgumentError: invalid base64>

### ISSUE THREAD

**Issue by rncain** [Skalar/google_distance_matrix#8]
```
Trace
ArgumentError - invalid base64:
  /Users/rcain/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/base64.rb:73:in `unpack'
  /Users/rcain/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/base64.rb:73:in `strict_decode64'
  /Users/rcain/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/base64.rb:89:in `urlsafe_decode64'
  google_business_api_url_signer (0.1.3) lib/google_business_api_url_signer/signer.rb:98:in `private_key_decoded'
  google_business_api_url_signer (0.1.3) lib/google_business_api_url_signer/signer.rb:57:in `signature_digest'
  google_business_api_url_signer (0.1.3) lib/google_business_api_url_signer/signer.rb:35:in `signature'
  google_business_api_url_signer (0.1.3) lib/google_business_api_url_signer/signer.rb:91:in `query_params_as_string_with_signature'
  google_business_api_url_signer (0.1.3) lib/google_business_api_url_signer/signer.rb:46:in `signed_url'
  google_business_api_url_signer (0.1.3) lib/google_business_api_url_signer.rb:23:in `add_signature'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/url_builder.rb:27:in `build_url'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/url_builder.rb:17:in `url'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/matrix.rb:91:in `url'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/matrix.rb:111:in `load_matrix'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/matrix.rb:67:in `data'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/routes_finder.rb:6:in `data'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/routes_finder.rb:146:in `block in routes_for_destination'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/routes_finder.rb:145:in `tap'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/routes_finder.rb:145:in `routes_for_destination'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/routes_finder.rb:26:in `routes_for'
  google_distance_matrix (0.1.3) lib/google_distance_matrix/routes_finder.rb:81:in `shortest_route_by_dista
...
```

I have an initializer that calls:
```
GoogleDistanceMatrix.configure_defaults do |config|
    config.google_business_api_client_id = "my-client"
    config.google_business_api_private_key = "my-key"
end
```

**Comment by rncain** [comment]
Sorry, not my day I had the client id and key reversed!
